spring:
  profiles:
    active: default

---

spring:
  profiles: default
hono:
  server:
    bindaddress: 0.0.0.0
  telemetry:
    downstream:
      host: qdrouter
      port: 5673

---

spring:
  profiles: activemq
hono:
  pathSeparator: .
  telemetry:
    downstream:
      host: localhost
      port: 5671