{{- if .Values.adapters.lora.enabled }}
apiVersion: v1
kind: Service
metadata:
  {{- $args := dict "dot" . "component" "adapter-lora-vertx" "name" "adapter-lora-vertx" }}
  {{- include "hono.metadata" $args | nindent 2 }}
spec:
  ports:
  - name: http
    port: 8080
    protocol: TCP
    targetPort: http
    nodePort: 32080
  - name: https
    port: 8443
    protocol: TCP
    targetPort: https
    nodePort: 32443
  selector:
    {{- include "hono.matchLabels" $args | nindent 4 }}
{{- if and ( eq .Values.useLoadBalancer true ) ( ne .Values.platform "openshift" ) }}
  type: LoadBalancer
{{ else }}
  type: NodePort
{{- end }}
{{- end }}
