{{if eq .Values.openshift true}}
---
apiVersion: v1
kind: Route
metadata:
  labels:
    app: hono-adapter-http-vertx
    version: "{{ .Chart.AppVersion }}"
    group: {{ .Values.project.groupId }}
  name: hono-adapter-http-vertx
spec:
  port:
    targetPort: 8080
  to:
    kind: Service
    name: hono-adapter-http-vertx
{{end}}
