{{- if eq .Values.platform "openshift" }}
---
apiVersion: v1
kind: Route
metadata:
  labels:
    app: hono-adapter-http-vertx
    version: "{{ .Chart.AppVersion }}"
    group: {{ .Values.project.groupId }}
  name: hono-adapter-http-vertx-sec
spec:
  port:
    targetPort: 8443
  tls:
    termination: passthrough
  to:
    kind: Service
    name: hono-adapter-http-vertx
{{- end }}
