{{if eq .Values.openshift true}}
---
apiVersion: v1
kind: Route
metadata:
  labels:
    app: amqp-messaging-network
    version: {{ .Chart.AppVersion }}
    group: {{ .Values.project.groupId }}
  name: hono-dispatch-router
spec:
  port:
    targetPort: 5671
  tls:
    termination: passthrough
  to:
    kind: Service
    name: hono-dispatch-router
{{end}}
