---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: amqp-messaging-network
    version: "{{ .Chart.AppVersion }}"
    group: {{ .Values.project.groupId }}
  name: hono-dispatch-router
spec:
  ports:
  - port: 5673
    protocol: TCP
    targetPort: 5673
  selector:
    app: amqp-messaging-network
    role: router
    group: {{ .Values.project.groupId }}
