apiVersion: v1
kind: Secret
metadata:
  name: hono-dispatch-router-conf
  labels:
    app: amqp-messaging-network
    version: "{{ .Chart.AppVersion }}"
    group: {{ .Values.project.groupId }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
type: Opaque
data:
  "qdrouter-key.pem": |-
    {{ .Files.Get "hono-demo-certs-jar/qdrouter-key.pem" | b64enc }}
  "qdrouter-cert.pem": |-
    {{ .Files.Get "hono-demo-certs-jar/qdrouter-cert.pem" | b64enc }}
  "trusted-certs.pem": |-
    {{ .Files.Get "hono-demo-certs-jar/trusted-certs.pem" | b64enc }}
  "qdrouterd-with-broker.json": |-
    {{ .Files.Get "config/qpid/qdrouterd-with-broker.json" | b64enc }}
