dist: bionic
language: java

services:
- docker

jdk:
- openjdk11

install: true # no need to call 'mvn install'

script:
  - mvn verify -B -e -Dmsg.count=400 -Dtest.env=true -DcreateJavadoc=true -Ddocker.host=unix:///var/run/docker.sock -Dservice.startup.timeout=600000 -Dmax.event-loop.execute-time=20000 -Pbuild-docker-image,run-tests -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn

env:
  global:
  - COMMIT=${TRAVIS_COMMIT::8}

after_script:
- bash <(curl -s https://codecov.io/bash)
