---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: hono-metrics
    version: "${project.version}"
    group: ${project.groupId}
  name: grafana
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hono-metrics
      role: grafana
      group: ${project.groupId}
  template:
    metadata:
      labels:
        app: hono-metrics
        role: grafana
        version: "${project.version}"
        group: ${project.groupId}
    spec:
      serviceAccountName: useroot
      containers:
      - env:
        - name: GF_PATHS_DATA
          value: /var/lib/grafana
        - name: GF_PATHS_LOGS
          value: /var/log/grafana
        - name: KUBERNETES_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        image: grafana/grafana:${grafana.version}
        imagePullPolicy: IfNotPresent
        livenessProbe:
          httpGet:
            port: 3000
          initialDelaySeconds: 20
          periodSeconds: 9
          timeoutSeconds: 1
        name: grafana
        readinessProbe:
          httpGet:
            port: 3000
          initialDelaySeconds: 5
          periodSeconds: 5
          timeoutSeconds: 1
        securityContext:
          privileged: false
        volumeMounts:
        - mountPath: /var/log/grafana
          name: grafana-logs
        - mountPath: /var/lib/grafana
          name: grafana-data
      volumes:
      - emptyDir: {}
        name: grafana-logs
      - emptyDir: {}
        name: grafana-data
