---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: hono-metrics
    version: "{{ .Chart.AppVersion }}"
    group: {{ .Values.project.groupId }}
  name: grafana
spec:
  ports:
    - nodePort: 31000
      port: 3000
      protocol: TCP
      targetPort: 3000
  selector:
    app: grafana
    release: {{ .Release.Name }}
  type: NodePort
