{{- define "hono.qdrouterd-with-broker.json" -}}
[
  ["router", {
    "id": "Hono.Example.Router",
    "mode": "standalone",
    "workerThreads": 3
  }],

  ["authServicePlugin", {
    "name": "Hono Auth",
    "host": "{{ .Release.Name }}-service-auth",
    "port": 5671,
    "sslProfile": "internal"
  }],

  ["sslProfile", {
    "name": "external",
    "protocols": "TLSv1.2",
    "caCertFile": "/etc/hono/trusted-certs.pem",
    "certFile": "/etc/hono/qdrouter-cert.pem",
    "privateKeyFile": "/etc/hono/qdrouter-key.pem"
  }],

  ["sslProfile", {
    "name": "internal",
    "protocols": "TLSv1.2",
    "caCertFile": "/etc/hono/trusted-certs.pem",
    "certFile": "/etc/hono/qdrouter-cert.pem",
    "privateKeyFile": "/etc/hono/qdrouter-key.pem",
    "uidFormat": "ou"
  }],

  ["listener", {
    "sslProfile": "external",
    "requireSsl": true,
    "host": "0.0.0.0",
    "port": 5671,
    "maxSessionFrames": 200,
    "linkCapacity": 100,
    "authenticatePeer": true,
    "saslMechanisms": "PLAIN",
    "saslPlugin": "Hono Auth"
  }],

  ["listener", {
    "host": "0.0.0.0",
    "port": 5672,
    "maxSessionFrames": 200,
    "linkCapacity": 100,
    "authenticatePeer": true,
    "saslMechanisms": "PLAIN",
    "saslPlugin": "Hono Auth"
  }],

  ["listener", {
    "sslProfile": "internal",
    "requireSsl": true,
    "host": "0.0.0.0",
    "port": 5673,
    "maxSessionFrames": 500,
    "linkCapacity": 100,
    "authenticatePeer": true,
    "saslMechanisms": "EXTERNAL"
  }],

  ["connector", {
    "sslProfile": "external",
    "name": "broker",
    "host": "{{ .Release.Name }}-artemis",
    "port": 5671,
    "role": "route-container",
    "saslUsername": "artemis",
    "saslPassword": "artemis",
    "verifyHostname": false
  }],

  ["linkRoute", {
    "prefix": "event/",
    "direction": "in",
    "connection": "broker"
  }],

  ["linkRoute", {
    "prefix": "event/",
    "direction": "out",
    "connection": "broker"
  }],

  ["address", {
    "prefix": "telemetry/",
    "distribution": "balanced"
  }],

  ["policy", {
    "maxConnections": 1000,
    "enableVhostPolicy": true,
    "defaultVhost": "hono"
  }],

  ["vhost", {
      "hostname": "hono",
      "maxConnections": 500,
      "maxConnectionsPerUser": 20,
      "maxConnectionsPerHost": 10,
      "allowUnknownUser": true,
      "groups": {
        "$default": {
          "remoteHosts": "*",
          "maxSessions": 10
        }
      }
  }],

  ["vhost", {
      "hostname": "hono-internal",
      "maxConnections": 50,
      "groups": {
        "Hono": {
          "users": "Eclipse IoT;Hono",
          "remoteHosts": "*",
          "maxSessions": 4,
          "maxMessageSize": 131072,
          "allowUserIdProxy": true,
          "allowAnonymousSender": true,
          "sources": "control/*, command/*",
          "targets": "telemetry/*, event/*, control/*, command_response/*"
        }
      }
  }],

  ["log", {
    "module": "DEFAULT",
    "enable": "info+"
  }]
]
{{- end }}
