{{if eq .Values.useLoadBalancer true}}
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: hono-service-device-registry
    version: "{{ .Chart.AppVersion }}"
    group: {{ .Values.project.groupId }}
    hono-metrics: prometheus
  name: ${hono.registration.service}-extlb
spec:
  type: LoadBalancer
  ports:
  - name: http
    port: 28080
    targetPort: 8080
  - name: https
    port: 28443
    targetPort: 8443
  selector:
    app: hono-service-device-registry
{{end}}
