{{- if .Values.deviceRegistryExample.enabled }}
apiVersion: v1
kind: Service
metadata:
  {{- $args := dict "dot" . "component" "service-device-registry" "name" "service-device-registry-ext" }}
  {{- include "hono.metadata" $args | nindent 2 }}
  {{- with .Values.deviceRegistryExample.svc.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  ports:
  - name: http
    port: 28080
    protocol: TCP
    targetPort: http
    nodePort: 31080
  - name: https
    port: 28443
    protocol: TCP
    targetPort: https
    nodePort: 31443
  selector:
    {{- include "hono.matchLabels" $args | nindent 4 }}
{{- if and ( eq .Values.useLoadBalancer true ) ( ne .Values.platform "openshift" ) }}
  type: LoadBalancer
{{- else }}
  type: NodePort
{{- end }}
{{- with .Values.deviceRegistryExample.svc.loadBalancerIP }}
  loadBalancerIP: {{ . | quote }}
{{- end }}
{{- end }}
