{{- if .Values.deviceRegistryDeployExample }}
{{- $args := dict "dot" . "component" "service-device-registry" "name" "service-device-registry-conf" -}}
apiVersion: v1
kind: Secret
metadata:
  {{- include "hono.metadata" $args | nindent 2 }}
type: Opaque
stringData:
  example-device-identities.json: |
    {{- .Files.Get "example/example-device-identities.json" | nindent 4 }}
  example-credentials.json: |
    {{- .Files.Get "example/example-credentials.json" | nindent 4 }}
  example-tenants.json: |
    {{- .Files.Get "example/example-tenants.json" | nindent 4 }}
  application.yml: |
    hono:
      app:
        maxInstances: 1
      auth:
        host: {{ .Release.Name }}-service-auth
        port: 5671
        trustStorePath: /etc/hono/trusted-certs.pem
        hostnameVerificationRequired: false
        name: Hono {{ $args.component }}
        validation:
          certPath: /etc/hono/auth-server-cert.pem
      registry:
        amqp:
          bindAddress: 0.0.0.0
          keyPath: /etc/hono/key.pem
          certPath: /etc/hono/cert.pem
        rest:
          bindAddress: 0.0.0.0
          keyPath: /etc/hono/key.pem
          certPath: /etc/hono/cert.pem
          insecurePortBindAddress: 0.0.0.0
          insecurePortEnabled: true
        svc:
          filename: /var/lib/hono/device-registry/device-identities.json
          saveToFile: true
      credentials:
        svc:
          filename: /var/lib/hono/device-registry/credentials.json
          saveToFile: true
      tenant:
        svc:
          filename: /var/lib/hono/device-registry/tenants.json
          saveToFile: true
      {{- include "hono.healthServerConfig" nil | nindent 6 }}
data:
  key.pem: {{ .Files.Get "hono-demo-certs-jar/device-registry-key.pem" | b64enc }}
  cert.pem: {{ .Files.Get "hono-demo-certs-jar/device-registry-cert.pem" | b64enc }}
  trusted-certs.pem: {{ .Files.Get "hono-demo-certs-jar/trusted-certs.pem" | b64enc }}
  auth-server-cert.pem: {{ .Files.Get "hono-demo-certs-jar/auth-server-cert.pem" | b64enc }}
{{- end }}
