{{if eq .Values.openshift true}}
---
apiVersion: v1
kind: Route
metadata:
  labels:
    app: hono-service-device-registry
    version: "{{ .Chart.AppVersion }}"
    group: {{ .Values.project.groupId }}
  name: hono-service-device-registry-http
spec:
  port:
    targetPort: 8080
  to:
    kind: Service
    name: hono-service-device-registry
{{end}}
