---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: hono-service-device-registry
    version: {{ .Chart.AppVersion }}
    group: {{ .Values.project.groupId }}
    hono-metrics: prometheus
  name: hono-service-device-registry
spec:
  ports:
  - name: amqps
    nodePort: 31671
    port: 5671
    protocol: TCP
    targetPort: 5671
  - name: http
    nodePort: 31080
    port: 8080
    protocol: TCP
    targetPort: 8080
  - name: https
    nodePort: 31443
    port: 8443
    protocol: TCP
    targetPort: 8443
  - name: health
    port: {{ .Values.monitoring.prometheus.port }}
  selector:
    app: hono-service-device-registry
    group: {{ .Values.project.groupId }}
  type: NodePort
