{{- if .Values.deviceRegistryExample.enabled }}
{{- $args := dict "dot" . "component" "service-device-registry" "name" "service-device-registry-conf" -}}
apiVersion: v1
kind: Secret
metadata:
  {{- include "hono.metadata" $args | nindent 2 }}
type: Opaque
stringData:
  {{- if not .Values.deviceRegistryExample.data.volumeName }}
  {{ .Values.deviceRegistryExample.data.devicesFile }}: |
    {{- .Files.Get "example/example-device-identities.json" | nindent 4 }}
  {{ .Values.deviceRegistryExample.data.credentialsFile }}: |
    {{- .Files.Get "example/example-credentials.json" | nindent 4 }}
  {{ .Values.deviceRegistryExample.data.tenantsFile }}: |
    {{- .Files.Get "example/example-tenants.json" | nindent 4 }}
  {{- end }}
  application.yml: |
    hono:
      app:
        maxInstances: 1
      auth:
        {{- if .Values.deviceRegistryExample.hono.auth }}
        {{- .Values.deviceRegistryExample.hono.auth | toYaml | nindent 8 }}
        {{- else }}
        host: {{ printf "%s-service-auth" .Release.Name | quote }}
        port: 5671
        trustStorePath: "/etc/hono/trusted-certs.pem"
        hostnameVerificationRequired: false
        name: {{ printf "Hono %s" $args.component | quote }}
        validation:
          certPath: "/etc/hono/auth-server-cert.pem"
        {{- end }}
      registry:
        amqp:
          {{- if .Values.deviceRegistryExample.hono.registry.amqp }}
          {{- .Values.deviceRegistryExample.hono.registry.amqp | toYaml | nindent 10 }}
          {{- else }}
          bindAddress: "0.0.0.0"
          keyPath: "/etc/hono/key.pem"
          certPath: "/etc/hono/cert.pem"
          {{- end }}
        rest:
          {{- if .Values.deviceRegistryExample.hono.registry.rest }}
          {{- .Values.deviceRegistryExample.hono.registry.rest | toYaml | nindent 10 }}
          {{- else }}
          bindAddress: "0.0.0.0"
          keyPath: "/etc/hono/key.pem"
          certPath: "/etc/hono/cert.pem"
          insecurePortEnabled: true
          insecurePortBindAddress: "0.0.0.0"
          {{- end }}
        svc:
          filename: "/var/lib/hono/device-registry/device-identities.json"
          saveToFile: true
      credentials:
        svc:
          filename: "/var/lib/hono/device-registry/credentials.json"
          saveToFile: true
      tenant:
        svc:
          filename: "/var/lib/hono/device-registry/tenants.json"
          saveToFile: true
      {{- include "hono.healthServerConfig" .Values.deviceRegistryExample.hono.healthCheck | nindent 6 }}
{{- if not .Values.deviceRegistryExample.extraSecretMounts }}
data:
  key.pem: {{ .Files.Get "hono-demo-certs-jar/device-registry-key.pem" | b64enc }}
  cert.pem: {{ .Files.Get "hono-demo-certs-jar/device-registry-cert.pem" | b64enc }}
  trusted-certs.pem: {{ .Files.Get "hono-demo-certs-jar/trusted-certs.pem" | b64enc }}
  auth-server-cert.pem: {{ .Files.Get "hono-demo-certs-jar/auth-server-cert.pem" | b64enc }}
{{- end }}
{{- end }}
