{{- if .Values.adapters.coap.enabled }}
{{- $args := dict "dot" . "component" "adapter-coap-vertx" "name" "adapter-coap-vertx-conf" -}}
apiVersion: v1
kind: Secret
metadata:
  {{- include "hono.metadata" $args | nindent 2 }}
type: Opaque
stringData:
  adapter.credentials: |
    {{- .Files.Get "example/coap-adapter.credentials" | nindent 4 }}
  application.yml: |
    hono:
      app:
        maxInstances: 1
      coap:
        bindAddress: 0.0.0.0
        insecurePortBindAddress: 0.0.0.0
        insecurePortEnabled: true
        keyPath: /etc/hono/key.pem
        certPath: /etc/hono/cert.pem
      {{- include "hono.healthServerConfig" nil | nindent 6 }}
      {{- include "hono.serviceClientConfig" $args | nindent 6 }}
data:
  key.pem: {{ .Files.Get "hono-demo-certs-jar/coap-adapter-key.pem" | b64enc }}
  cert.pem: {{ .Files.Get "hono-demo-certs-jar/coap-adapter-cert.pem" | b64enc }}
  trusted-certs.pem: {{ .Files.Get "hono-demo-certs-jar/trusted-certs.pem" | b64enc }}
{{ end }}
