baseurl = "https://www.eclipse.org/hono/"
languageCode = "en-us"
title = "Eclipse Hono"
theme = "hugo-material-docs"
metadataformat = "toml"
canonifyurls = false
# Enable Google Analytics by entering your tracking id
googleAnalytics = "UA-91336727-1"
pluralizeListTitles = "false"

[params]
	# General information
	author = "The Eclipse Hono Project"
	description = "A set of micro-services for connecting millions of devices."
	copyright = "The Eclipse Hono Project"
  version = ""
  logo = "images/logo-32x32px.png"
  favicon = "images/favicon.ico"

	# Repository
	provider = "GitHub"
	repo_url = "https://github.com/eclipse/hono"

  # CI Server
  hipp_url = "https://hudson.eclipse.org/hono"

	permalink = "#"

	# Custom assets
	custom_css = ["css/hono.css"]
	custom_js  = []

	# Syntax highlighting theme
	highlight_css  = ""

[params.palette]
	primary = "orange"
	accent  = "teal"

[params.font]
	text = "Ubuntu"
	code = "Ubuntu Mono"

[social]
	twitter = ""
	github  = "eclipse/hono"
	irc     = "#eclipse-hono"
	email   = "hono-dev@eclipse.org"
	mailinglist = "https://dev.eclipse.org/mailman/listinfo/hono-dev"


[[menu.main]]
  name   = "Concepts"
  identifier = "Concepts"
  url    = "/concepts/"
  weight = 180

[[menu.main]]
	name   = "User Guide"
	identifier = "User Guide"
	url    = "/user-guide/"
  weight = 200

[[menu.main]]
  name   = "Admin Guide"
  identifier = "Admin Guide"
  url    = "/admin-guide/"
  weight = 300

[[menu.main]]
	name   = "Developer Guide"
	identifier = "Developer Guide"
	url    = "/dev-guide/"
  weight = 380

[[menu.main]]
  name   = "API"
  identifier = "api"
  url    = "/api/"
  weight = 400

[[menu.main]]
  name   = "Deployment"
  identifier = "Deployment"
  url    = "/deployment/"
  weight = 470

[[menu.main]]
  name   = "Architecture"
  identifier = "Architecture"
  url    = "/architecture/"
  weight = 500

[[menu.main]]
  name   = "Community"
  identifier = "Community"
  url    = "/community/"
  weight = 600

[blackfriday]
	smartypants	= true
	fractions = true
	smartDashes = true
	plainIDAnchors = true
