hono:
  app:
    maxInstances: 1
    healthCheckPort: 8088
    healthCheckBindAddress: 0.0.0.0
  mqtt:
    bindAddress: 0.0.0.0
    insecurePortBindAddress: 0.0.0.0
    insecurePortEnabled: true
    keyPath: /run/secrets/mqtt-adapter-key.pem
    certPath: /run/secrets/mqtt-adapter-cert.pem
    jmsVendorPropsEnabled: true
    maxPayloadSize: 8096
  messaging:
    name: 'Hono MQTT Adapter'
    host: ${hono.messaging.host}
    port: 5671
    username: ${hono.adapter.mqtt.username}
    password: ${hono.adapter.mqtt.password}
    trustStorePath: ${hono.trustStore.path}
  registration:
    name: 'Hono MQTT Adapter'
    host: ${hono.registration.host}
    port: 5671
    username: ${hono.adapter.mqtt.username}
    password: ${hono.adapter.mqtt.password}
    trustStorePath: ${hono.trustStore.path}
  credentials:
    name: 'Hono MQTT Adapter'
    host: ${hono.registration.host}
    port: 5671
    username: ${hono.adapter.mqtt.username}
    password: ${hono.adapter.mqtt.password}
    trustStorePath: ${hono.trustStore.path}
  tenant:
    name: 'Hono MQTT Adapter'
    host: ${hono.registration.host}
    port: 5671
    username: ${hono.adapter.mqtt.username}
    password: ${hono.adapter.mqtt.password}
    trustStorePath: ${hono.trustStore.path}
  metric:
    reporter:
      graphite:
        active: true
        host: influxdb.hono
        port: 2003
# disable spring boot actuator endpoints, enable metrics
endpoints:
  enabled: false
  metrics:
    enabled: true

