---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: hono-service-auth
    version: {{ .Chart.AppVersion }}
    group: {{ .Values.project.groupId }}
    hono-metrics: prometheus
  name: hono-service-auth
spec:
  ports:
  - name: amqps
    port: 5671
    protocol: TCP
    targetPort: 5671
  - name: health
    port: {{ .Values.monitoring.prometheus.port }}
  selector:
    app: hono-service-auth
    group: {{ .Values.project.groupId }}
