{{if eq .Values.openshift true}}
---
apiVersion: v1
kind: Route
metadata:
  labels:
    app: hono-service-auth
    version: "{{ .Chart.AppVersion }}"
    group: {{ .Values.project.groupId }}
  name: hono-service-auth
spec:
  port:
    targetPort: 5671
  tls:
    termination: passthrough
  to:
    kind: Service
    name: hono-service-auth
{{end}}
    
