apiVersion: v1
kind: Service
metadata:
  {{- $args := dict "dot" . "component" "service-auth" "name" "service-auth" }}
  {{- include "hono.metadata" $args | nindent 2 }}
    hono-metrics: prometheus
spec:
  ports:
  - name: amqps
    port: 5671
    protocol: TCP
    targetPort: amqps
  selector:
    {{- include "hono.matchLabels" $args | nindent 4 }}
