version: '3.0'

networks:
  hono-net:
    driver: overlay

services:

  qdrouter:
    image: eclipsehono/dispatch-router:${project.version}
    networks:
      - hono-net
    command: /usr/sbin/qdrouterd -c /etc/hono/qdrouter/qdrouterd-with-broker.json
    ports:
      - "15671:5671"
      - "15672:5672"

  broker:
    image: eclipsehono/broker:${project.version}
    networks:
      - hono-net
    ports:
      - "5672:5672"

  hono:
    image: eclipsehono/hono-server:${project.version}
    networks:
      - hono-net
    ports:
      - "5671:5671"
    environment:
      - HONO_DOWNSTREAM_HOST=qdrouter
      - HONO_DOWNSTREAM_PORT=5673
      - HONO_DOWNSTREAM_KEY_PATH=/etc/hono/certs/hono-key.pem
      - HONO_DOWNSTREAM_CERT_PATH=/etc/hono/certs/hono-cert.pem
      - HONO_DOWNSTREAM_TRUST_STORE_PATH=/etc/hono/certs/trusted-certs.pem
      - HONO_REGISTRATION_SIGNING_SECRET=signing-secret
      - HONO_SERVER_BIND_ADDRESS=0.0.0.0
      - HONO_SERVER_KEY_PATH=/etc/hono/certs/hono-key.pem
      - HONO_SERVER_CERT_PATH=/etc/hono/certs/hono-cert.pem
      - HONO_SERVER_INSECURE_PORT_ENABLED=false
      - HONO_SERVER_MAX_INSTANCES=1
      - LOGGING_CONFIG=classpath:logback-spring.xml
      - SPRING_PROFILES_ACTIVE=default,dev
    volumes:
      - /home/hono/registration

  rest-adapter:
    image: eclipsehono/hono-adapter-rest-vertx:${project.version}
    networks:
      - hono-net
    ports:
      - "8080:8080"
      - "8443:8443"
    environment:
      - HONO_CLIENT_NAME=Hono REST Adapter
      - HONO_CLIENT_HOST=hono
      - HONO_CLIENT_PORT=5671
      - HONO_CLIENT_USERNAME=rest-adapter
      - HONO_CLIENT_PASSWORD=secret
      - HONO_CLIENT_TRUST_STORE_PATH=/etc/hono/certs/trusted-certs.pem
      - HONO_HTTP_BIND_ADDRESS=0.0.0.0
      - HONO_HTTP_INSECURE_PORT_BIND_ADDRESS=0.0.0.0
      - HONO_HTTP_INSECURE_PORT_ENABLED=true
      - HONO_HTTP_KEY_PATH=/etc/hono/certs/rest-adapter-key.pem
      - HONO_HTTP_CERT_PATH=/etc/hono/certs/rest-adapter-cert.pem
      - HONO_HTTP_MAX_INSTANCES=1
      - SPRING_PROFILES_ACTIVE=dev

  mqtt-adapter:
    image: eclipsehono/hono-adapter-mqtt-vertx:${project.version}
    networks:
      - hono-net
    ports:
      - "1883:1883"
      - "8883:8883"
    environment:
      - HONO_CLIENT_NAME=Hono MQTT Adapter
      - HONO_CLIENT_HOST=hono
      - HONO_CLIENT_PORT=5671
      - HONO_CLIENT_USERNAME=mqtt-adapter
      - HONO_CLIENT_PASSWORD=secret
      - HONO_CLIENT_TRUST_STORE_PATH=/etc/hono/certs/trusted-certs.pem
      - HONO_MQTT_BIND_ADDRESS=0.0.0.0
      - HONO_MQTT_INSECURE_PORT_BIND_ADDRESS=0.0.0.0
      - HONO_MQTT_INSECURE_PORT_ENABLED=true
      - HONO_MQTT_KEY_PATH=/etc/hono/certs/mqtt-adapter-key.pem
      - HONO_MQTT_CERT_PATH=/etc/hono/certs/mqtt-adapter-cert.pem
      - HONO_MQTT_MAX_INSTANCES=1
      - SPRING_PROFILES_ACTIVE=dev
