version: '3.1'

networks:
  hono-net:
    driver: overlay

services:

  influxdb:
    image: influxdb:1.2.2
    networks:
      hono-net:
        aliases:
          - influxdb.hono
    ports:
      - "8086:8086"
      - "8083:8083"
      - "2003:2003"
    environment:
      - INFLUXDB_GRAPHITE_ENABLED=true
      - INFLUXDB_ADMIN_ENABLED=true

  grafana:
    image: eclipsehono/grafana:${project.version}
    command: ./bin/grafana-server
    networks:
      hono-net:
        aliases:
          - grafana.hono
    ports:
      - "3000:3000"

  hono-dispatch-router:
    image: eclipsehono/hono-dispatch-router:${project.version}
    networks:
      hono-net:
        aliases:
          - hono-dispatch-router.hono
    command: /usr/sbin/qdrouterd -c /etc/hono/qdrouter/qdrouterd-with-broker.json
    ports:
      - "15671:5671"
      - "15672:5672"

  hono-artemis:
    image: eclipsehono/hono-artemis:${project.version}
    networks:
      hono-net:
        aliases:
          - hono-artemis.hono
    ports:
      - "5672:5672"

  hono-service-auth:
    image: eclipsehono/hono-service-auth:${project.version}
    networks:
      hono-net:
        aliases:
          - hono-service-auth.hono
    environment:
      - HONO_AUTH_BIND_ADDRESS=0.0.0.0
      - HONO_AUTH_KEY_PATH=/etc/hono/certs/auth-server-key.pem
      - HONO_AUTH_CERT_PATH=/etc/hono/certs/auth-server-cert.pem
      - HONO_AUTH_MAX_INSTANCES=1
      - LOGGING_CONFIG=classpath:logback-spring.xml
      - SPRING_PROFILES_ACTIVE=authentication-impl,dev

  hono-service-messaging:
    image: eclipsehono/hono-service-messaging:${project.version}
    networks:
      hono-net:
        aliases:
          - hono-service-messaging.hono
    ports:
      - "5671:5671"
    environment:
      - HONO_AUTH_HOST=hono-service-auth.hono
      - HONO_AUTH_TRUST_STORE_PATH=/etc/hono/certs/trusted-certs.pem
      - HONO_AUTH_NAME=Hono Messaging
      - HONO_AUTH_VALIDATION_CERT_PATH=/etc/hono/certs/auth-server-cert.pem
      - HONO_DOWNSTREAM_HOST=hono-dispatch-router.hono
      - HONO_DOWNSTREAM_PORT=5673
      - HONO_DOWNSTREAM_KEY_PATH=/etc/hono/certs/hono-messaging-key.pem
      - HONO_DOWNSTREAM_CERT_PATH=/etc/hono/certs/hono-messaging-cert.pem
      - HONO_DOWNSTREAM_TRUST_STORE_PATH=/etc/hono/certs/trusted-certs.pem
      - HONO_MESSAGING_BIND_ADDRESS=0.0.0.0
      - HONO_MESSAGING_KEY_PATH=/etc/hono/certs/hono-messaging-key.pem
      - HONO_MESSAGING_CERT_PATH=/etc/hono/certs/hono-messaging-cert.pem
      - HONO_MESSAGING_INSECURE_PORT_ENABLED=false
      - HONO_MESSAGING_MAX_INSTANCES=1
      - HONO_MESSAGING_VALIDATION_SHARED_SECRET="g#aWO!BUm7aj*#%X*VGXKFhxkhNrMNj0"
      - HONO_METRIC_REPORTER_GRAPHITE_ACTIVE=true
      - HONO_METRIC_REPORTER_GRAPHITE_HOST=influxdb.hono
      - HONO_METRIC_REPORTER_GRAPHITE_PORT=2003
      - LOGGING_CONFIG=classpath:logback-spring.xml
      - SPRING_PROFILES_ACTIVE=default,dev

  hono-service-device-registry:
    image: eclipsehono/hono-service-device-registry:${project.version}
    networks:
      hono-net:
        aliases:
          - hono-service-device-registry.hono
    ports:
      - "26671:5671"
    environment:
      - HONO_AUTH_HOST=hono-service-auth.hono
      - HONO_AUTH_TRUST_STORE_PATH=/etc/hono/certs/trusted-certs.pem
      - HONO_AUTH_NAME=Hono Device Registry
      - HONO_AUTH_VALIDATION_CERT_PATH=/etc/hono/certs/auth-server-cert.pem
      - HONO_DEVICE_REGISTRY_BIND_ADDRESS=0.0.0.0
      - HONO_DEVICE_REGISTRY_KEY_PATH=/etc/hono/certs/device-registry-key.pem
      - HONO_DEVICE_REGISTRY_CERT_PATH=/etc/hono/certs/device-registry-cert.pem
      - HONO_DEVICE_REGISTRY_INSECURE_PORT_ENABLED=false
      - HONO_DEVICE_REGISTRY_MAX_INSTANCES=1
      - HONO_DEVICE_REGISTRY_SIGNING_SHARED_SECRET="g#aWO!BUm7aj*#%X*VGXKFhxkhNrMNj0"
      - LOGGING_CONFIG=classpath:logback-spring.xml
      - SPRING_PROFILES_ACTIVE=default,dev
    volumes:
      - /home/hono/registration

  hono-adapter-rest-vertx:
    image: eclipsehono/hono-adapter-rest-vertx:${project.version}
    networks:
      hono-net:
        aliases:
          - hono-adapter-rest-vertx.hono
    ports:
      - "8080:8080"
      - "8443:8443"
    environment:
      - HONO_CLIENT_NAME=Hono REST Adapter
      - HONO_CLIENT_HOST=hono-service-messaging.hono
      - HONO_CLIENT_PORT=5671
      - HONO_CLIENT_USERNAME=rest-adapter@HONO
      - HONO_CLIENT_PASSWORD=rest-secret
      - HONO_CLIENT_TRUST_STORE_PATH=/etc/hono/certs/trusted-certs.pem
      - HONO_REGISTRATION_NAME=Hono REST Adapter
      - HONO_REGISTRATION_HOST=hono-service-device-registry.hono
      - HONO_REGISTRATION_PORT=5671
      - HONO_REGISTRATION_USERNAME=rest-adapter@HONO
      - HONO_REGISTRATION_PASSWORD=rest-secret
      - HONO_REGISTRATION_TRUST_STORE_PATH=/etc/hono/certs/trusted-certs.pem
      - HONO_HTTP_BIND_ADDRESS=0.0.0.0
      - HONO_HTTP_INSECURE_PORT_BIND_ADDRESS=0.0.0.0
      - HONO_HTTP_INSECURE_PORT_ENABLED=true
      - HONO_HTTP_KEY_PATH=/etc/hono/certs/rest-adapter-key.pem
      - HONO_HTTP_CERT_PATH=/etc/hono/certs/rest-adapter-cert.pem
      - HONO_HTTP_MAX_INSTANCES=1
      - SPRING_PROFILES_ACTIVE=dev

  hono-adapter-mqtt-vertx:
    image: eclipsehono/hono-adapter-mqtt-vertx:${project.version}
    networks:
      hono-net:
        aliases:
          - hono-adapter-mqtt-vertx.hono
    ports:
      - "1883:1883"
      - "8883:8883"
    environment:
      - HONO_CLIENT_NAME=Hono MQTT Adapter
      - HONO_CLIENT_HOST=hono-service-messaging.hono
      - HONO_CLIENT_PORT=5671
      - HONO_CLIENT_USERNAME=mqtt-adapter@HONO
      - HONO_CLIENT_PASSWORD=mqtt-secret
      - HONO_CLIENT_TRUST_STORE_PATH=/etc/hono/certs/trusted-certs.pem
      - HONO_REGISTRATION_NAME=Hono MQTT Adapter
      - HONO_REGISTRATION_HOST=hono-service-device-registry.hono
      - HONO_REGISTRATION_PORT=5671
      - HONO_REGISTRATION_USERNAME=mqtt-adapter@HONO
      - HONO_REGISTRATION_PASSWORD=mqtt-secret
      - HONO_REGISTRATION_TRUST_STORE_PATH=/etc/hono/certs/trusted-certs.pem
      - HONO_MQTT_BIND_ADDRESS=0.0.0.0
      - HONO_MQTT_INSECURE_PORT_BIND_ADDRESS=0.0.0.0
      - HONO_MQTT_INSECURE_PORT_ENABLED=true
      - HONO_MQTT_KEY_PATH=/etc/hono/certs/mqtt-adapter-key.pem
      - HONO_MQTT_CERT_PATH=/etc/hono/certs/mqtt-adapter-cert.pem
      - HONO_MQTT_MAX_INSTANCES=1
      - SPRING_PROFILES_ACTIVE=dev
