---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: amqp-messaging-network
    version: "{{ .Chart.AppVersion }}"
    group: {{ .Values.project.groupId }}
  name: hono-artemis
spec:
  ports:
  - port: 5671
    protocol: TCP
    targetPort: 5671
  selector:
    app: amqp-messaging-network
    role: broker
    group: {{ .Values.project.groupId }}
