{{- if .Values.amqpMessagingNetworkDeployExample -}}
apiVersion: v1
kind: Service
metadata:
  {{- $args := dict "dot" . "component" "amqp-messaging-network-broker" "name" "artemis" }}
  {{- include "hono.metadata" $args | nindent 2 }}
spec:
  ports:
  - name: amqps
    port: 5671
    protocol: TCP
    targetPort: amqps
  selector:
    {{- include "hono.matchLabels" $args | nindent 4 }}
{{- end }}
