{{- if and ( eq .Values.amqpMessagingNetworkExample.enabled true ) ( eq .Values.amqpMessagingNetworkExample.broker.type "artemis" ) }}
apiVersion: v1
kind: Secret
metadata:
  {{- $args := dict "dot" . "component" "amqp-messaging-network-broker" "name" "artemis-conf" }}
  {{- include "hono.metadata" $args | nindent 2 }}
type: Opaque
stringData:
  "artemis-broker.xml": |
    {{- .Files.Get "config/artemis/artemis-broker.xml" | nindent 4 }}
  "artemis-bootstrap.xml": |
    {{- .Files.Get "config/artemis/artemis-bootstrap.xml" | nindent 4 }}
  "artemis-users.properties": |
    {{- .Files.Get "config/artemis/artemis-users.properties" | nindent 4 }}
  "artemis-roles.properties": |
    {{- .Files.Get "config/artemis/artemis-roles.properties" | nindent 4 }}
  "login.config": |
    {{- .Files.Get "config/artemis/login.config" | nindent 4 }}
  "logging.properties": |
    {{- .Files.Get "config/artemis/logging.properties" | nindent 4 }}
  "artemis.profile": |
    {{- .Files.Get "config/artemis/artemis.profile" | nindent 4 }}
data:
  "artemisKeyStore.p12": {{ .Files.Get "hono-demo-certs-jar/artemisKeyStore.p12" | b64enc }}
  "trustStore.jks": {{ .Files.Get "hono-demo-certs-jar/trustStore.jks" | b64enc }}
{{- end }}
