spec:
  template:
    metadata:
      labels:
        role: grafana
    spec:
      volumes:
      - name: grafana-logs
        emptyDir: {}
      - name: grafana-data
        emptyDir: {}
      containers:
      - image: grafana/grafana:${grafana.version}
        name: eclipsehono-grafana
        readinessProbe:
          initialDelaySeconds: 5
          periodSeconds: 5
          timeoutSeconds: 1
          httpGet:
            port: 3000
        livenessProbe:
          initialDelaySeconds: 20
          periodSeconds: 9
          timeoutSeconds: 1
          httpGet:
            port: 3000
        volumeMounts:
        - name: grafana-logs
          mountPath: /var/log/grafana
        - name: grafana-data
          mountPath: /var/lib/grafana
        env:
        - name: GF_PATHS_DATA
          value: /var/lib/grafana
        - name: GF_PATHS_LOGS
          value: /var/log/grafana
