{{- if and (eq .Values.platform "openshift") .Values.adapters.kura.enabled }}
apiVersion: v1
kind: Route
metadata:
  {{- $args := dict "dot" . "component" "adapter-kura" "name" "adapter-kura" }}
  {{- include "hono.metadata" $args | nindent 2 }}
spec:
  port:
    targetPort: 1883
  to:
    kind: Service
    name: {{ .Release.Name }}-adapter-kura
{{ end }}
