---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: hono-adapter-kura
    version: "{{ .Chart.AppVersion }}"
    group: {{ .Values.project.groupId }}
    hono-metrics: prometheus
  name: hono-adapter-kura
spec:
  ports:
  - name: mqtt
    port: 1883
    protocol: TCP
    targetPort: mqtt
    nodePort: 31884
  - name: secure-mqtt
    port: 8883
    protocol: TCP
    targetPort: secure-mqtt
    nodePort: 30884
  selector:
    app: hono-adapter-kura
    group: {{ .Values.project.groupId }}
{{- if and ( eq .Values.useLoadBalancer true ) ( ne .Values.platform "openshift" ) }}
  type: LoadBalancer
{{ else }}
  type: NodePort
{{- end }}
