#
# Copyright (c) 2021 Contributors to the Eclipse Foundation
#
# See the NOTICE file(s) distributed with this work for additional
# information regarding copyright ownership.
#
# This program and the accompanying materials are made available under the
# terms of the Eclipse Public License 2.0 which is available at
# http://www.eclipse.org/legal/epl-2.0
#
# SPDX-License-Identifier: EPL-2.0
#

useLoadBalancer: true

messagingNetworkTypes:
- "amqp"
- "kafka"

amqpMessagingNetworkExample:
  enabled: true
  insecurePortEnabled: false
  dispatchRouter:
    uidFormat: "n"
    adapterUids: "hono.eclipseprojects.io"
    tlsKeysSecret: "sandbox-tls"
    resources:
      requests:
        cpu: "50m"
        memory: "64Mi"
      limits:
        cpu: "1"
        memory: "256Mi"
  broker:
    artemis:
      resources:
        requests:
          cpu: "50m"
          memory: "600Mi"
        limits:
          cpu: "1"
          memory: "600Mi"

adapters:
  http:
    enabled: true
    imageName: "eclipsehono/hono-adapter-http-native"
    hono:
      http:
        insecurePortEnabled: false
        bindAddress: "0.0.0.0"
        keyPath: "/opt/hono/tls/tls.key"
        certPath: "/opt/hono/tls/tls.crt"
        idleTimeout: 20
        jmsVendorPropsEnabled: true
        maxPayloadSize: 8096
        tenantIdleTimeout: "1h"
    tlsKeysSecret: "sandbox-tls"
    cmdLineArgs:
    - "-Xmx96m"
    resources:
      requests:
        cpu: "50m"
        memory: "120Mi"
      limits:
        memory: "120Mi"

  mqtt:
    enabled: true
    imageName: "eclipsehono/hono-adapter-mqtt-native"
    hono:
      mqtt:
        insecurePortEnabled: false
        bindAddress: "0.0.0.0"
        keyPath: "/opt/hono/tls/tls.key"
        certPath: "/opt/hono/tls/tls.crt"
        jmsVendorPropsEnabled: true
        maxPayloadSize: 8096
        tenantIdleTimeout: "1h"
        maxConnections: 200
    tlsKeysSecret: "sandbox-tls"
    cmdLineArgs:
    - "-Xmx96m"
    resources:
      requests:
        cpu: "50m"
        memory: "120Mi"
      limits:
        memory: "120Mi"

  amqp:
    enabled: true
    imageName: "eclipsehono/hono-adapter-amqp-native"
    hono:
      amqp:
        insecurePortEnabled: false
        bindAddress: "0.0.0.0"
        keyPath: "/opt/hono/tls/tls.key"
        certPath: "/opt/hono/tls/tls.crt"
        tenantIdleTimeout: "1h"
        maxConnections: 200
    tlsKeysSecret: "sandbox-tls"
    cmdLineArgs:
    - "-Xmx96m"
    resources:
      requests:
        cpu: "50m"
        memory: "120Mi"
      limits:
        memory: "120Mi"

  coap:
    enabled: true
    imageName: "eclipsehono/hono-adapter-coap-native"
    hono:
      coap:
        insecurePortEnabled: false
        bindAddress: "0.0.0.0"
        port: 5684
        keyPath: "/opt/hono/tls/tls.key"
        certPath: "/opt/hono/tls/tls.crt"
        tenantIdleTimeout: "1h"
    tlsKeysSecret: "sandbox-tls"
    cmdLineArgs:
    - "-Xmx96m"
    resources:
      requests:
        cpu: "50m"
        memory: "120Mi"
      limits:
        memory: "120Mi"

  kura:
    enabled: false

  lora:
    enabled: false

  amqpMessagingNetworkSpec:
    keyPath: "/opt/hono/tls/tls.key"
    certPath: "/opt/hono/tls/tls.crt"
    hostnameVerificationRequired: false
  commandAndControlSpec:
    keyPath: "/opt/hono/tls/tls.key"
    certPath: "/opt/hono/tls/tls.crt"
    hostnameVerificationRequired: false

authServer:
  imageName: "eclipsehono/hono-service-auth-native"
  cmdLineArgs:
  - "-Xmx48m"
  resources:
    requests:
      cpu: "50m"
      memory: "60Mi"
    limits:
      cpu:
      memory: "60Mi"

deviceRegistryExample:
  type: "embedded"
  hono:
    registry:
      amqp:
        bindAddress: "0.0.0.0"
        keyPath: "/opt/hono/tls/tls.key"
        certPath: "/opt/hono/tls/tls.crt"
      http:
        authenticationRequired: false
        insecurePortEnabled: false
        bindAddress: "0.0.0.0"
        keyPath: "/opt/hono/tls/tls.key"
        certPath: "/opt/hono/tls/tls.crt"
      svc:
        maxDevicesPerTenant: 10
  tlsKeysSecret: "sandbox-tls"
  embeddedJdbcDeviceRegistry:
    resources:
      requests:
        cpu: "100m"
        memory: "400Mi"
      limits:
        cpu:
        memory: "400Mi"

dataGridExample:
  enabled: true
  resources:
    requests:
      cpu: "50m"
      memory: "100Mi"
    limits:
      cpu: "1"
      memory: "200Mi"

commandRouterService:
  imageName: "eclipsehono/hono-service-command-router-native"
  tlsKeysSecret: "sandbox-tls"
  cmdLineArgs:
  - "-Xmx96m"
  resources:
    requests:
      cpu: "50m"
      memory: "120Mi"
    limits:
      memory: "120Mi"

# assumes bitnami/kafka chart version ^26.8
kafka:
  controller:
    extraConfig: |
      group.initial.rebalance.delay.ms=0
      offsets.topic.replication.factor=1
      transaction.state.log.min.isr=1
      transaction.state.log.replication.factor=1
      log.flush.interval.messages=1000
      log.flush.interval.ms=1000
      log.retention.bytes=10485760
      log.retention.check.interval.ms=300000
      log.retention.hours=1
      log.segment.bytes=10485760
  tls:
    type: "PEM"
    pemChainIncluded: true
    existingSecret: "sandbox-tls"
  externalAccess:
    enabled: true
    autoDiscovery:
      enabled: false
    broker:
      service:
        type: "LoadBalancer"
        loadBalancerIPs:
        - "hono.eclipseprojects.io"
        nodePorts: []
    controller:
      service:
        type: "LoadBalancer"
        loadBalancerIPs:
        - "hono.eclipseprojects.io"
        nodePorts: []

  serviceAccount:
    create: false
  rbac:
    create: false

jaegerBackendExample:
  enabled: false
