hono:
  app:
    maxInstances: 1
    healthCheckPort: ${vertx.health.port}
    healthCheckBindAddress: 0.0.0.0
  mqtt:
    bindAddress: 0.0.0.0
    insecurePortBindAddress: 0.0.0.0
    insecurePortEnabled: true
    keyPath: /run/secrets/hono.eclipse.org-key.pem
    certPath: /run/secrets/hono.eclipse.org-cert.pem
    jmsVendorPropsEnabled: true
    maxPayloadSize: 8096
  messaging:
    name: 'Hono MQTT Adapter'
    host: ${hono.amqp-network.service}${service.suffix}
    port: 5673
    amqpHostname: hono-internal
  registration:
    name: 'Hono MQTT Adapter'
    host: ${hono.registration.service}${service.suffix}
    port: 5672
    credentialsPath: /run/secrets/mqtt-adapter.credentials
  credentials:
    name: 'Hono MQTT Adapter'
    host: ${hono.registration.service}${service.suffix}
    port: 5672
    credentialsPath: /run/secrets/mqtt-adapter.credentials
  tenant:
    name: 'Hono MQTT Adapter'
    host: ${hono.registration.service}${service.suffix}
    port: 5672
    credentialsPath: /run/secrets/mqtt-adapter.credentials
  command:
    name: 'Hono MQTT Adapter'
    host: ${hono.amqp-network.service}${service.suffix}
    port: 5673
    amqpHostname: hono-internal
