hono:
  app:
    maxInstances: 1
  healthCheck:
    port: ${vertx.health.port}
    bindAddress: 0.0.0.0
  auth:
    host: ${hono.auth.service}${service.suffix}
    port: 5671
    trustStorePath: /run/secrets/trusted-certs.pem
    name: 'Hono Device Registry'
    validation:
      certPath: /run/secrets/auth-server-cert.pem
  registry:
    amqp:
      bindAddress: 0.0.0.0
      keyPath: /run/secrets/hono.eclipse.org-key.pem
      certPath: /run/secrets/hono.eclipse.org-cert.pem
      insecurePortBindAddress: 0.0.0.0
      insecurePortEnabled: true
    rest:
      bindAddress: 0.0.0.0
      keyPath: /run/secrets/hono.eclipse.org-key.pem
      certPath: /run/secrets/hono.eclipse.org-cert.pem
      insecurePortBindAddress: 0.0.0.0
      insecurePortEnabled: true
    svc:
      filename: /var/lib/hono/device-registry/device-identities.json
      saveToFile: true
      modificationEnabled: false
  credentials:
    svc:
      filename: /var/lib/hono/device-registry/credentials.json
      saveToFile: true
      modificationEnabled: false
  tenant:
    svc:
      filename: /var/lib/hono/device-registry/tenants.json
      saveToFile: true
      modificationEnabled: false
