hono:
  app:
    maxInstances: 1
    healthCheckPort: ${vertx.health.port}
    healthCheckBindAddress: 0.0.0.0
  amqp:
    bindAddress: 0.0.0.0
    insecurePortBindAddress: 0.0.0.0
    insecurePortEnabled: true
    keyPath: /run/secrets/hono.eclipse.org-key.pem
    certPath: /run/secrets/hono.eclipse.org-cert.pem
  messaging:
    name: 'Hono AMQP Adapter'
    amqpHostname: hono-internal
    host: ${hono.amqp-network.service}${service.suffix}
    port: 5673
  registration:
    name: 'Hono AMQP Adapter'
    host: ${hono.registration.service}${service.suffix}
    port: 5672
    credentialsPath: /run/secrets/amqp-adapter.credentials
  credentials:
    name: 'Hono AMQP Adapter'
    host: ${hono.registration.service}${service.suffix}
    port: 5672
    credentialsPath: /run/secrets/amqp-adapter.credentials
  tenant:
    name: 'Hono AMQP Adapter'
    host: ${hono.registration.service}${service.suffix}
    port: 5672
    credentialsPath: /run/secrets/amqp-adapter.credentials
  command:
    name: 'Hono AMQP Adapter'
    amqpHostname: hono-internal
    host: ${hono.amqp-network.service}${service.suffix}
    port: 5673
