#
# Copyright (c) 2019, 2021 Contributors to the Eclipse Foundation
#
# See the NOTICE file(s) distributed with this work for additional
# information regarding copyright ownership.
#
# This program and the accompanying materials are made available under the
# terms of the Eclipse Public License 2.0 which is available at
# http://www.eclipse.org/legal/epl-2.0
#
# SPDX-License-Identifier: EPL-2.0
#
hono:
  app:
    maxInstances: 1
  healthCheck:
    port: ${vertx.health.port}
    bindAddress: 0.0.0.0
    keyPath: /run/secrets/hono.eclipse.org-key.pem
    certPath: /run/secrets/hono.eclipse.org-cert.pem
  kura:
    bindAddress: 0.0.0.0
    insecurePortBindAddress: 0.0.0.0
    insecurePortEnabled: true
    keyPath: /run/secrets/hono.eclipse.org-key.pem
    certPath: /run/secrets/hono.eclipse.org-cert.pem
    maxPayloadSize: 8096
    tenantIdleTimeout: 1h
    maxConnections: 200
  messaging:
    name: 'Hono Kura Adapter'
    host: ${hono.amqp-network.service}${service.suffix}
    port: 5673
    amqpHostname: hono-internal
  registration:
    name: 'Hono Kura Adapter'
    host: ${hono.registration.service}${service.suffix}
    port: 5672
    credentialsPath: /run/secrets/kura-adapter.credentials
  credentials:
    name: 'Hono Kura Adapter'
    host: ${hono.registration.service}${service.suffix}
    port: 5672
    credentialsPath: /run/secrets/kura-adapter.credentials
  tenant:
    name: 'Hono Kura Adapter'
    host: ${hono.registration.service}${service.suffix}
    port: 5672
    credentialsPath: /run/secrets/kura-adapter.credentials
  commandRouter:
    name: 'Hono Kura Adapter'
    host: ${hono.command-router.service}${service.suffix}
    port: 5672
    credentialsPath: /run/secrets/kura-adapter.credentials
  command:
    name: 'Hono Kura Adapter'
    host: ${hono.amqp-network.service}${service.suffix}
    port: 5673
    amqpHostname: hono-internal
