#
# Copyright (c) 2019 Contributors to the Eclipse Foundation
#
# See the NOTICE file(s) distributed with this work for additional
# information regarding copyright ownership.
#
# This program and the accompanying materials are made available under the
# terms of the Eclipse Public License 2.0 which is available at
# http://www.eclipse.org/legal/epl-2.0
#
# SPDX-License-Identifier: EPL-2.0
#

global:
  scrape_interval: 5s

scrape_configs:

# The "tasks." prefix allows to resolve the IP addresses of the service instance
# containers instead of just the Virtual IP of the (logical) service

- job_name: hono-service-auth
  metrics_path: /prometheus
  scheme: https
  tls_config:
    insecure_skip_verify: true
  dns_sd_configs:
  - names:
      - tasks.${hono.auth.service}${service.suffix}
    type: A
    port: ${prometheus.scraping.port}
    refresh_interval: 10s

- job_name: hono-service-device-registry
  metrics_path: /prometheus
  scheme: https
  tls_config:
    insecure_skip_verify: true
  dns_sd_configs:
  - names:
      - tasks.${hono.registration.service}${service.suffix}
    type: A
    port: ${prometheus.scraping.port}
    refresh_interval: 10s

- job_name: hono-adapter-amqp-vertx
  metrics_path: /prometheus
  scheme: https
  tls_config:
    insecure_skip_verify: true
  dns_sd_configs:
  - names:
      - tasks.${hono.adapter-amqp.service}${service.suffix}
    type: A
    port: ${prometheus.scraping.port}
    refresh_interval: 5s

- job_name: hono-adapter-http-vertx
  metrics_path: /prometheus
  scheme: https
  tls_config:
    insecure_skip_verify: true
  dns_sd_configs:
  - names:
      - tasks.${hono.adapter-http.service}${service.suffix}
    type: A
    port: ${prometheus.scraping.port}
    refresh_interval: 5s

- job_name: hono-adapter-mqtt-vertx
  metrics_path: /prometheus
  scheme: https
  tls_config:
    insecure_skip_verify: true
  dns_sd_configs:
  - names:
      - tasks.${hono.adapter-mqtt.service}${service.suffix}
    type: A
    port: ${prometheus.scraping.port}
    refresh_interval: 5s

- job_name: hono-adapter-kura-vertx
  metrics_path: /prometheus
  scheme: https
  tls_config:
    insecure_skip_verify: true
  dns_sd_configs:
  - names:
      - tasks.${hono.adapter-kura.service}${service.suffix}
    type: A
    port: ${prometheus.scraping.port}
    refresh_interval: 5s
