hono:
  app:
    maxInstances: 1
    healthCheckPort: ${vertx.health.port}
    healthCheckBindAddress: 0.0.0.0
  mqtt:
    bindAddress: 0.0.0.0
    insecurePortBindAddress: 0.0.0.0
    insecurePortEnabled: true
    keyPath: ${secret.path}/mqtt-adapter-key.pem
    certPath: ${secret.path}/mqtt-adapter-cert.pem
  messaging:
    name: 'Hono MQTT Adapter'
    host: messaging${service.suffix}
    port: 5672
  registration:
    name: 'Hono MQTT Adapter'
    host: ${hono.registration.service}${service.suffix}
    port: 5671
    credentialsPath: ${secret.path}/mqtt-adapter.credentials
    trustStorePath: ${secret.path}/trusted-certs.pem
  credentials:
    name: 'Hono MQTT Adapter'
    host: ${hono.registration.service}${service.suffix}
    port: 5671
    credentialsPath: ${secret.path}/mqtt-adapter.credentials
    trustStorePath: ${secret.path}/trusted-certs.pem
  tenant:
    name: 'Hono MQTT Adapter'
    host: ${hono.registration.service}${service.suffix}
    port: 5671
    credentialsPath: ${secret.path}/mqtt-adapter.credentials
    trustStorePath: ${secret.path}/trusted-certs.pem
  devcon:
    name: 'Hono MQTT Adapter'
    host: ${hono.registration.service}${service.suffix}
    port: 5671
    credentialsPath: ${secret.path}/mqtt-adapter.credentials
    trustStorePath: ${secret.path}/trusted-certs.pem
  command:
    name: 'Hono MQTT Adapter'
    host: messaging${service.suffix}
    port: 5672
