hono:
  app:
    maxInstances: 1
    healthCheckPort: ${vertx.health.port}
    healthCheckBindAddress: 0.0.0.0
  coap:
    bindAddress: 0.0.0.0
    insecurePortBindAddress: 0.0.0.0
    insecurePortEnabled: true
  messaging:
    name: 'Hono COAP Adapter'
    amqpHostname: hono-internal
    host: ${hono.amqp-network.host}
    port: 5673
    keyPath: ${secret.path}/coap-adapter-key.pem
    certPath: ${secret.path}/coap-adapter-cert.pem
    trustStorePath: ${secret.path}/trusted-certs.pem
  registration:
    name: 'Hono COAP Adapter'
    host: ${hono.registration.host}
    port: 5671
    credentialsPath: ${secret.path}/coap-adapter.credentials
    trustStorePath: ${secret.path}/trusted-certs.pem
  credentials:
    name: 'Hono COAP Adapter'
    host: ${hono.registration.host}
    port: 5671
    credentialsPath: ${secret.path}/coap-adapter.credentials
    trustStorePath: ${secret.path}/trusted-certs.pem
  tenant:
    name: 'Hono COAP Adapter'
    host: ${hono.registration.host}
    port: 5671
    credentialsPath: ${secret.path}/coap-adapter.credentials
    trustStorePath: ${secret.path}/trusted-certs.pem
  command:
    name: 'Hono COAP Adapter'
    amqpHostname: hono-internal
    host: ${hono.amqp-network.host}
    port: 5673
    keyPath: ${secret.path}/coap-adapter-key.pem
    certPath: ${secret.path}/coap-adapter-cert.pem
    trustStorePath: ${secret.path}/trusted-certs.pem
