hono:
  app:
    maxInstances: 1
  healthCheck:
    port: ${vertx.health.port}
    bindAddress: 0.0.0.0
    keyPath: ${secret.path}/kura-adapter-key.pem
    certPath: ${secret.path}/kura-adapter-cert.pem
  kura:
    bindAddress: 0.0.0.0
    insecurePortBindAddress: 0.0.0.0
    insecurePortEnabled: true
    keyPath: ${secret.path}/kura-adapter-key.pem
    certPath: ${secret.path}/kura-adapter-cert.pem
  messaging:
    name: 'Hono Kura Adapter'
    host: messaging${service.suffix}
    port: 5672
  registration:
    name: 'Hono Kura Adapter'
    host: ${hono.registration.service}${service.suffix}
    port: 5671
    credentialsPath: ${secret.path}/kura-adapter.credentials
    trustStorePath: ${secret.path}/trusted-certs.pem
  credentials:
    name: 'Hono Kura Adapter'
    host: ${hono.registration.service}${service.suffix}
    port: 5671
    credentialsPath: ${secret.path}/kura-adapter.credentials
    trustStorePath: ${secret.path}/trusted-certs.pem
  tenant:
    name: 'Hono Kura Adapter'
    host: ${hono.registration.service}${service.suffix}
    port: 5671
    credentialsPath: ${secret.path}/kura-adapter.credentials
    trustStorePath: ${secret.path}/trusted-certs.pem
  deviceConnection:
    name: 'Hono Kura Adapter'
    host: ${hono.registration.service}${service.suffix}
    port: 5671
    credentialsPath: ${secret.path}/kura-adapter.credentials
    trustStorePath: ${secret.path}/trusted-certs.pem
  command:
    name: 'Hono Kura Adapter'
    host: messaging${service.suffix}
    port: 5672
  metrics:
    legacy: true

# disable spring boot actuator endpoints
endpoints:
  enabled: false

management:
  metrics:
    export:
      graphite:
        host: influxdb.hono
        port: 2003
