hono:
  app:
    maxInstances: 1
    healthCheckPort: ${vertx.health.port}
    healthCheckBindAddress: 0.0.0.0
  amqp:
    bindAddress: 0.0.0.0
    insecurePortBindAddress: 0.0.0.0
    insecurePortEnabled: true
    keyPath: ${secret.path}/amqp-adapter-key.pem
    certPath: ${secret.path}/amqp-adapter-cert.pem
  messaging:
    name: 'Hono AMQP Adapter'
    amqpHostname: hono-internal
    host: hono-dispatch-router.hono
    port: 5673
    keyPath: ${secret.path}/amqp-adapter-key.pem
    certPath: ${secret.path}/amqp-adapter-cert.pem
    trustStorePath: ${secret.path}/trusted-certs.pem
  registration:
    name: 'Hono AMQP Adapter'
    host: ${hono.registration.host}
    port: 5671
    credentialsPath: ${secret.path}/amqp-adapter.credentials
    trustStorePath: ${secret.path}/trusted-certs.pem
  credentials:
    name: 'Hono AMQP Adapter'
    host: ${hono.registration.host}
    port: 5671
    credentialsPath: ${secret.path}/amqp-adapter.credentials
    trustStorePath: ${secret.path}/trusted-certs.pem
  tenant:
    name: 'Hono AMQP Adapter'
    host: ${hono.registration.host}
    port: 5671
    credentialsPath: ${secret.path}/amqp-adapter.credentials
    trustStorePath: ${secret.path}/trusted-certs.pem
  command:
    name: 'Hono AMQP Adapter'
    amqpHostname: hono-internal
    host: hono-dispatch-router.hono
    port: 5673
    keyPath: ${secret.path}/amqp-adapter-key.pem
    certPath: ${secret.path}/amqp-adapter-cert.pem
    trustStorePath: ${secret.path}/trusted-certs.pem
