---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: hono-metrics
    version: "${project.version}"
    group: ${project.groupId}
  name: influxdb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hono-metrics
      role: influxdb
      group: ${project.groupId}
  template:
    metadata:
      labels:
        app: hono-metrics
        role: influxdb
        version: "${project.version}"
        group: ${project.groupId}
    spec:
      containers:
      - args:
        - -config
        - /etc/hono/influxdb.conf
        env:
        - name: KUBERNETES_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        image: influxdb:${influxdb.version}
        imagePullPolicy: IfNotPresent
        name: influxdb
        ports:
        - containerPort: 8086
          name: api
          protocol: TCP
        - containerPort: 8083
          name: admin
          protocol: TCP
        - containerPort: 2003
          name: graphite
          protocol: TCP
        readinessProbe:
          initialDelaySeconds: 5
          periodSeconds: 5
          tcpSocket:
            port: 2003
          timeoutSeconds: 1
        livenessProbe:
          initialDelaySeconds: 20
          periodSeconds: 9
          tcpSocket:
            port: 2003
          timeoutSeconds: 1
        securityContext:
          privileged: false
        volumeMounts:
        - mountPath: /var/lib/influxdb
          name: influxdb-storage
        - mountPath: /etc/hono
          name: conf
          readOnly: true
      volumes:
      - emptyDir: {}
        name: influxdb-storage
      - name: conf
        secret:
          secretName: influxdb-conf
