spring:
  jmx:
    enabled: false
  profiles:
    active: receiver,ssl

hono:
  client:
    host: localhost
    reconnectAttempts: 5

connection:
  retryInterval: 1000

tenant:
  id: DEFAULT_TENANT
device:
  id: 4711

---

spring:
  profiles: receiver

hono:
  client:
    port: 15671

address:
  resolver:
    cacheNegativeTimeToLive: 0 #discard failed DNS lookup results immediately
    cacheMaxTimeToLive: 0 #support DNS based service resolution
    rotateServers: true
    queryTimeout: 2000

message:
  type: all

---

spring:
  profiles: ssl
hono:
  client:
    hostnameVerificationRequired: false
    trustStorePath: target/config/hono-demo-certs-jar/trusted-certs.pem

---

spring:
  profiles: amqp-adapter-cli

amqp:
  host: 127.0.0.1
  port: 4040

message:
  address: telemetry/DEFAULT_TENANT/4711

username: sensor1@DEFAULT_TENANT

password: hono-secret

payload: '{"temp": 5}'

---

spring:
  profiles: command

hono:
  client:
    port: 15671

command:
  timeoutInSeconds: 60

tenant:
  id: DEFAULT_TENANT

device:
  id: 4711

