---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  labels:
    app: hono-adapter-mqtt-vertx
    version: "${project.version}"
    group: ${project.groupId}
  name: hono-adapter-mqtt-vertx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hono-adapter-mqtt-vertx
      group: ${project.groupId}
  template:
    metadata:
      labels:
        app: hono-adapter-mqtt-vertx
        version: "${project.version}"
        group: ${project.groupId}
    spec:
      containers:
      - image: eclipse/hono-adapter-mqtt-vertx:${project.version}
        imagePullPolicy: IfNotPresent
        name: eclipse-hono-adapter-mqtt-vertx
        ports:
        - containerPort: ${vertx.health.port}
          protocol: TCP
        - containerPort: 8883
          protocol: TCP
        - containerPort: 1883
          protocol: TCP
        securityContext:
          privileged: false
        env:
        - name: SPRING_CONFIG_LOCATION
          value: file:///etc/hono/
        - name: SPRING_PROFILES_ACTIVE
          value: dev
        - name: LOGGING_CONFIG
          value: classpath:logback-spring.xml
        - name: _JAVA_OPTIONS
          value: "${default-java-options}"
        - name: KUBERNETES_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        volumeMounts:
        - mountPath: /etc/hono
          name: conf
          readOnly: true
        resources:
          limits:
            memory: "256Mi"
        livenessProbe:
          httpGet:
            path: /liveness
            port: ${vertx.health.port}
            scheme: HTTP
          initialDelaySeconds: 180
        readinessProbe:
          httpGet:
            path: /readiness
            port: ${vertx.health.port}
            scheme: HTTP
          initialDelaySeconds: 10
      volumes:
      - name: conf
        secret:
          secretName: hono-adapter-mqtt-vertx-conf
