hono:
  app:
    maxInstances: 1
    healthCheckPort: 8088
    healthCheckBindAddress: 0.0.0.0
  http:
    bindAddress: 0.0.0.0
    insecurePortBindAddress: 0.0.0.0
    insecurePortEnabled: true
    keyPath: ${secret.path}/http-adapter-key.pem
    certPath: ${secret.path}/http-adapter-cert.pem
  messaging:
    name: 'Hono HTTP Adapter'
    host: ${hono.messaging.host}
    port: 5671
    credentialsPath: ${secret.path}/http-adapter.credentials
    trustStorePath: ${secret.path}/trusted-certs.pem
  registration:
    name: 'Hono HTTP Adapter'
    host: ${hono.registration.host}
    port: 5671
    credentialsPath: ${secret.path}/http-adapter.credentials
    trustStorePath: ${secret.path}/trusted-certs.pem
  credentials:
    name: 'Hono HTTP Adapter'
    host: ${hono.registration.host}
    port: 5671
    credentialsPath: ${secret.path}/http-adapter.credentials
    trustStorePath: ${secret.path}/trusted-certs.pem
  tenant:
    name: 'Hono HTTP Adapter'
    host: ${hono.registration.host}
    port: 5671
    credentialsPath: ${secret.path}/http-adapter.credentials
    trustStorePath: ${secret.path}/trusted-certs.pem
  metric:
    reporter:
      graphite:
        active: true
        host: influxdb.hono
        port: 2003
# disable spring boot actuator endpoints, enable metrics
endpoints:
  enabled: false
  metrics:
    enabled: true
