apiVersion: v1
kind: Service
metadata:
  {{- $args := dict "dot" . "component" "adapter-amqp-vertx" "name" "adapter-amqp-vertx" }}
  {{- include "hono.metadata" $args | nindent 2 }}
  {{- with .Values.adapters.amqp.svc.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  ports:
  - name: amqp
    port: 5672
    protocol: TCP
    targetPort: amqp
    nodePort: 32672
  - name: amqps
    port: 5671
    protocol: TCP
    targetPort: amqps
    nodePort: 32671
  selector:
    {{- include "hono.matchLabels" $args | nindent 4 }}
{{- if and ( eq .Values.useLoadBalancer true ) ( ne .Values.platform "openshift" ) }}
  type: LoadBalancer
{{- else }}
  type: NodePort
{{- end }}
{{- with .Values.adapters.amqp.svc.loadBalancerIP }}
  loadBalancerIP: {{ . | quote }}
{{- end }}
