{{- if eq .Values.platform "openshift" }}
---
apiVersion: v1
kind: Route
metadata:
  labels:
    app: hono-adapter-amqp-vertx
    provider: fabric8
    version: "{{ .Chart.AppVersion }}"
    group: {{ .Values.project.groupId }}
  name: hono-adapter-amqp-vertx-sec
spec:
  port:
    targetPort: 5671
  tls:
    termination: passthrough
  to:
    kind: Service
    name: hono-adapter-amqp-vertx
{{- end }}
