---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: hono-adapter-mqtt-vertx
    version: {{ .Chart.AppVersion }}
    group: {{ .Values.project.groupId }}
    hono-metrics: prometheus
  name: hono-adapter-mqtt-vertx
spec:
  ports:
  - name: mqtt
    nodePort: 31883
    port: 1883
    protocol: TCP
    targetPort: 1883
  - name: secure-mqtt
    nodePort: 30883
    port: 8883
    protocol: TCP
    targetPort: 8883
  - name: health
    port: {{ .Values.monitoring.prometheus.port }}
  selector:
    app: hono-adapter-mqtt-vertx
    group: {{ .Values.project.groupId }}
  type: NodePort
