{{if eq .Values.openshift true}}
---
apiVersion: v1
kind: Route
metadata:
  labels:
    app: hono-adapter-mqtt-vertx
    provider: fabric8
    version: "{{ .Chart.AppVersion }}"
    group: {{ .Values.project.groupId }}
  name: hono-adapter-mqtt-vertx
spec:
  port:
    targetPort: 1883
  to:
    kind: Service
    name: hono-adapter-mqtt-vertx
{{end}}
