spring:
  profiles:
    active: receiver

hono:
  client:
    host: localhost
    hostnameVerificationRequired: false
    trustStorePath: ../demo-certs/certs/trusted-certs.pem

tenant:
  id: DEFAULT_TENANT
device:
  id: 4711

---

spring:
  profiles: receiver
hono:
  client:
    port: 15671
    username: user1@HONO
    password: pw

---

spring:
  profiles: sender
hono:
  client:
    port: 5671
    username: hono-client
    password: secret
