---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: hono-service-auth
    version: "${project.version}"
    group: ${project.groupId}
    hono-metrics: prometheus
  name: hono-service-auth
spec:
  ports:
  - name: amqps
    port: 5671
    protocol: TCP
    targetPort: 5671
  - name: health
    port: ${prometheus.scraping.port}
  selector:
    app: hono-service-auth
    group: ${project.groupId}
